':sparkles: Feature':
  - 'src/app/**/*'
  - 'public/**/*'
':page_facing_up: Documentation':
  - LICENSE
  - README.md
  - '**/*.md'
':fire_extinguisher: Test':
  - '**/*.test.tsx'
  - '**/*.test.ts'
  - '**/*.spec.tsx'
  - '**/*.spec.ts'
  - 'e2e/**/*'
':package: Package':
  - pnpm-lock.yaml
':gear: Environment':
  - .github/**/*
  - bin/**/*
  - .eslintignore
  - .eslintrc.json
  - .gitignore
  - .nvmrc
  - next-env.d.ts
  - next.config.mjs
  - package.json
  - playwright.config.ts
  - renovate.json
  - tsconfig.json
  - vitest.config.ts
':police_officer: Security':
  - SECURITY.md
':lipstick: Design':
  - '**/*.css'
  